### ISSUE TITLE
aabbs.csv not found when downloading

### ISSUE THREAD

**Issue by takatoyamada** [synthesiaresearch/humanrf#27]
I found "actorshq/dataset/download_manager.py" returns the following error.
It seems the provided dataset doesn't include aabbs.csv (I couldn't see the actual file in my file system), so something might happen on the server side.
I was wondering if someone could check it.

```
./actorshq/dataset/download_manager.py actorshq_access_4x.yaml ./data/actorhq --actor Actor01 --sequence Sequence1 --scale 4 --frame_start 1 --frame_stop 2
Reading links ....
Downloading scene.json
Downloading RGB and mask files ...: 100%|
Downloading calibration.csv
Downloading occupancy_grids.tar.gz
Downloading light_annotations.csv
Downloading aabbs.csv
Traceback (most recent call last):
  File "/workspaces/humanrf/./actorshq/dataset/download_manager.py", line 240, in <module>
    main()
  File "/workspaces/humanrf/./actorshq/dataset/download_manager.py", line 225, in main
    download_dataset(
  File "/workspaces/humanrf/./actorshq/dataset/download_manager.py", line 197, in download_dataset
    download_lazy(
  File "/workspaces/humanrf/./actorshq/dataset/download_manager.py", line 31, in download_lazy
    with open(target_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/actorhq/Actor01/Sequence1/data/actorhq/Actor01/Sequence1/aabbs.csv'
```

**Comment by chunjins** [comment]
Have you solved it? I have the same problem

**Comment by chunjins** [comment]
I solved it by changing
`download_lazy(
        links[actor][sequence]["aabbs"],
        local_sequence_folder / dataset_paths.aabbs_path,
    )`
to 
`download_lazy(
        links[actor][sequence]["aabbs"],
        dataset_paths.aabbs_path,
    )`
